name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job_1_name_version:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: run entrypoint
        run: |
          echo "$(cat version).$GITHUB_RUN_NUMBER" > .version
          cat .version
          echo $GITHUB_WORKFLOW
          echo $GITHUB_RUN_ID
          echo $GITHUB_RUN_NUMBER
          echo $GITHUB_ACTION
          echo $GITHUB_ACTIONS
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_EVENT_PATH
          echo $GITHUB_WORKSPACE
          echo $GITHUB_SHA
          echo $GITHUB_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_BASE_REF
          echo $GITHUB_SERVER_URL
          echo $GITHUB_API_URL
          echo $GITHUB_GRAPHQL_URL

  job_2_name_tag:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/busybox:1.35.0-glibc
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: run entrypoint
        run: sh ./files/entrypoint_tag.sh
