name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: create tag
        run: |
          echo "$(cat version).$GITHUB_RUN_NUMBER" > .version
          echo $GITHUB_SHA > .hash
          echo "latest,$(cat version),$(cat version).$GITHUB_RUN_NUMBER" > .tags
          cat .tags

  job_2_name_tag:
    needs: tag
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/busybox:1.35.0-glibc
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: run entrypoint
        run: ls
