name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job_1_name_version:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: name of this
        run: |
          pwd
          ls
          sh ./files/entrypoint.sh

  job_2_name_tag:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/busybox:1.35.0-glibc
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: look
        run: |
          pwd
          ls
          sh ./files/entrypoint_tag.sh
