name: Deploy
on: [workflow_dispatch]
jobs:
  job_1_name:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      options: echo "hello world"
      
  job_2_name:
    runs-on: ubuntu-20.04
    steps:
    - name: name of this
      run: |
        echo $(pwd)
        echo "hello world"
