name: Deploy
on: [workflow_dispatch]
jobs:
  job_1_name:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      credentials:
        username: chicagomg
        password: ${{ secrets.token }}
    steps:
      - name: name of this
        run: |
          echo $(pwd)
          echo "hello world 2022"
          bash ./files/entrypoint.sh

  job_2_name:
    runs-on: ubuntu-20.04
    steps:
    - name: name of this
      run: |
        echo $(pwd)
        echo "hello world"
