name: Deploy
on: [workflow_dispatch]
jobs:
  job_1_name:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
      options: echo "hello world"
      steps:
        - name: name of this
          run: |
            echo $(pwd)

  job_2_name:
    runs-on: ubuntu-20.04
    steps:
    - name: name of this
      run: |
        echo $(pwd)
        echo "hello world"
