name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: create tag
        run: |
          echo "$(cat version).$GITHUB_RUN_NUMBER" > .version
          echo $GITHUB_SHA > .hash
          echo "latest,$(cat version),$(cat version).$GITHUB_RUN_NUMBER" > .tags
      - id: out
        run: echo "test=$(cat .tags)" >> $GITHUB_OUTPUT
    outputs:
      output_tag: ${{ steps.out.outputs.test }}

  publish:
    needs: tag
    runs-on: ubuntu-20.04
    steps:
      - name: run entrypoint
        run: echo ${{ needs.tag.outputs.output_tag }} > mrt
      - name: cat mrt
        run: cat mrt 
