name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  job_1_name:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      #image: public.ecr.aws/docker/library/bash:5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: run ls
        run: ls
      - name: name of this
        run: |
          sh ./files/entrypoint.sh

  job_2_name:
    runs-on: ubuntu-20.04
    steps:
    - name: name of this
      run: |
        echo $(pwd)
        echo "hello world"
