name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: create tag
        run: |
          echo "$(cat version).$GITHUB_RUN_NUMBER" > .version
          echo $GITHUB_SHA > .hash
          echo "latest,$(cat version),$(cat version).$GITHUB_RUN_NUMBER" > .tags
          pwd
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: kotik85
          path: |
            .version
          retention-days: 5


  second:
    needs: tag
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/bash:5
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: before download artifact
        run: |
          ls -la
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: kotik85
      - name: artifact here?
        run: |
          ls -la

  publisher:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/chicagomg/publisher:1.0
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - uses: actions/checkout@main
      - name: give execution permition
        run: chmod +x /plugin/entrypoint.sh
      - name: Login to GHCR 
        uses: docker/login-action@v1  
        with: 
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.github_token }}
      - name: Run build script
        run: /plugin/entrypoint.sh
        shell: bash
